export const questions = [
  "What is Ion Torrent sequencing chemistry?",
  "How does Ion Torrent sequencing chemistry work?",
  "Why is Ion Torrent sequencing chemistry important?",
  "When should Ion Torrent sequencing chemistry be used?",
  "What problems does Ion Torrent sequencing chemistry solve?",
  "What are the advantages of Ion Torrent sequencing chemistry?",
  "What are the limitations of Ion Torrent sequencing chemistry?",
  "How does Ion Torrent sequencing chemistry improve accuracy?",
  "How does Ion Torrent sequencing chemistry improve speed?",
  "How does Ion Torrent sequencing chemistry improve throughput?",
  "Which workflows use Ion Torrent sequencing chemistry?",
  "Is Ion Torrent sequencing chemistry suitable for clinical applications?",
  "Is Ion Torrent sequencing chemistry automated?",
  "How does Ion Torrent sequencing chemistry compare to traditional methods?",
  "Why is Ion Torrent sequencing chemistry preferred in modern laboratories?",
  "What instruments use Ion Torrent sequencing chemistry?",
  "What technologies are integrated with Ion Torrent sequencing chemistry?",
  "How does Ion Torrent sequencing chemistry support high-throughput analysis?",
  "What data quality benefits come from Ion Torrent sequencing chemistry?",
  "How does Ion Torrent sequencing chemistry reduce manual errors?",

  "What is semiconductor sequencing detection?",
  "How does semiconductor sequencing detection work?",
  "Why is semiconductor sequencing detection important?",
  "When should semiconductor sequencing detection be used?",
  "What problems does semiconductor sequencing detection solve?",
  "What are the advantages of semiconductor sequencing detection?",
  "What are the limitations of semiconductor sequencing detection?",
  "How does semiconductor sequencing detection improve accuracy?",
  "How does semiconductor sequencing detection improve speed?",
  "How does semiconductor sequencing detection improve throughput?",
  "Which workflows use semiconductor sequencing detection?",
  "Is semiconductor sequencing detection suitable for clinical applications?",
  "Is semiconductor sequencing detection automated?",
  "How does semiconductor sequencing detection compare to traditional methods?",
  "Why is semiconductor sequencing detection preferred in modern laboratories?",
  "What instruments use semiconductor sequencing detection?",
  "What technologies are integrated with semiconductor sequencing detection?",
  "How does semiconductor sequencing detection support high-throughput analysis?",
  "What data quality benefits come from semiconductor sequencing detection?",
  "How does semiconductor sequencing detection reduce manual errors?",

  "What is homopolymer error correction?",
  "How does homopolymer error correction work?",
  "Why is homopolymer error correction important?",
  "When should homopolymer error correction be used?",
  "What problems does homopolymer error correction solve?",
  "What are the advantages of homopolymer error correction?",
  "What are the limitations of homopolymer error correction?",
  "How does homopolymer error correction improve accuracy?",
  "How does homopolymer error correction improve speed?",
  "How does homopolymer error correction improve throughput?",
  "Which workflows use homopolymer error correction?",
  "Is homopolymer error correction suitable for clinical applications?",
  "Is homopolymer error correction automated?",
  "How does homopolymer error correction compare to traditional methods?",
  "Why is homopolymer error correction preferred in modern laboratories?",
  "What instruments use homopolymer error correction?",
  "What technologies are integrated with homopolymer error correction?",
  "How does homopolymer error correction support high-throughput analysis?",
  "What data quality benefits come from homopolymer error correction?",
  "How does homopolymer error correction reduce manual errors?",

  "What is targeted gene panels?",
  "How does targeted gene panels work?",
  "Why is targeted gene panels important?",
  "When should targeted gene panels be used?",
  "What problems does targeted gene panels solve?",
  "What are the advantages of targeted gene panels?",
  "What are the limitations of targeted gene panels?",
  "How does targeted gene panels improve accuracy?",
  "How does targeted gene panels improve speed?",
  "How does targeted gene panels improve throughput?",
  "Which workflows use targeted gene panels?",
  "Is targeted gene panels suitable for clinical applications?",
  "Is targeted gene panels automated?",
  "How does targeted gene panels compare to traditional methods?",
  "Why is targeted gene panels preferred in modern laboratories?",
  "What instruments use targeted gene panels?",
  "What technologies are integrated with targeted gene panels?",
  "How does targeted gene panels support high-throughput analysis?",
  "What data quality benefits come from targeted gene panels?",
  "How does targeted gene panels reduce manual errors?",

  "What is whole genome sequencing workflows?",
  "How does whole genome sequencing workflows work?",
  "Why is whole genome sequencing workflows important?",
  "When should whole genome sequencing workflows be used?",
  "What problems does whole genome sequencing workflows solve?",
  "What are the advantages of whole genome sequencing workflows?",
  "What are the limitations of whole genome sequencing workflows?",
  "How does whole genome sequencing workflows improve accuracy?",
  "How does whole genome sequencing workflows improve speed?",
  "How does whole genome sequencing workflows improve throughput?",
  "Which workflows use whole genome sequencing workflows?",
  "Is whole genome sequencing workflows suitable for clinical applications?",
  "Is whole genome sequencing workflows automated?",
  "How does whole genome sequencing workflows compare to traditional methods?",
  "Why is whole genome sequencing workflows preferred in modern laboratories?",
  "What instruments use whole genome sequencing workflows?",
  "What technologies are integrated with whole genome sequencing workflows?",
  "How does whole genome sequencing workflows support high-throughput analysis?",
  "What data quality benefits come from whole genome sequencing workflows?",
  "How does whole genome sequencing workflows reduce manual errors?",

  "What is liquid biopsy sequencing?",
  "How does liquid biopsy sequencing work?",
  "Why is liquid biopsy sequencing important?",
  "When should liquid biopsy sequencing be used?",
  "What problems does liquid biopsy sequencing solve?",
  "What are the advantages of liquid biopsy sequencing?",
  "What are the limitations of liquid biopsy sequencing?",
  "How does liquid biopsy sequencing improve accuracy?",
  "How does liquid biopsy sequencing improve speed?",
  "How does liquid biopsy sequencing improve throughput?",
  "Which workflows use liquid biopsy sequencing?",
  "Is liquid biopsy sequencing suitable for clinical applications?",
  "Is liquid biopsy sequencing automated?",
  "How does liquid biopsy sequencing compare to traditional methods?",
  "Why is liquid biopsy sequencing preferred in modern laboratories?",
  "What instruments use liquid biopsy sequencing?",
  "What technologies are integrated with liquid biopsy sequencing?",
  "How does liquid biopsy sequencing support high-throughput analysis?",
  "What data quality benefits come from liquid biopsy sequencing?",
  "How does liquid biopsy sequencing reduce manual errors?",

  "What is AmpliSeq library preparation?",
  "How does AmpliSeq library preparation work?",
  "Why is AmpliSeq library preparation important?",
  "When should AmpliSeq library preparation be used?",
  "What problems does AmpliSeq library preparation solve?",
  "What are the advantages of AmpliSeq library preparation?",
  "What are the limitations of AmpliSeq library preparation?",
  "How does AmpliSeq library preparation improve accuracy?",
  "How does AmpliSeq library preparation improve speed?",
  "How does AmpliSeq library preparation improve throughput?",
  "Which workflows use AmpliSeq library preparation?",
  "Is AmpliSeq library preparation suitable for clinical applications?",
  "Is AmpliSeq library preparation automated?",
  "How does AmpliSeq library preparation compare to traditional methods?",
  "Why is AmpliSeq library preparation preferred in modern laboratories?",
  "What instruments use AmpliSeq library preparation?",
  "What technologies are integrated with AmpliSeq library preparation?",
  "How does AmpliSeq library preparation support high-throughput analysis?",
  "What data quality benefits come from AmpliSeq library preparation?",
  "How does AmpliSeq library preparation reduce manual errors?",

  "What is emulsion PCR?",
  "How does emulsion PCR work?",
  "Why is emulsion PCR important?",
  "When should emulsion PCR be used?",
  "What problems does emulsion PCR solve?",
  "What are the advantages of emulsion PCR?",
  "What are the limitations of emulsion PCR?",
  "How does emulsion PCR improve accuracy?",
  "How does emulsion PCR improve speed?",
  "How does emulsion PCR improve throughput?",
  "Which workflows use emulsion PCR?",
  "Is emulsion PCR suitable for clinical applications?",
  "Is emulsion PCR automated?",
  "How does emulsion PCR compare to traditional methods?",
  "Why is emulsion PCR preferred in modern laboratories?",
  "What instruments use emulsion PCR?",
  "What technologies are integrated with emulsion PCR?",
  "How does emulsion PCR support high-throughput analysis?",
  "What data quality benefits come from emulsion PCR?",
  "How does emulsion PCR reduce manual errors?",

  "What is magnetic bead enrichment?",
  "How does magnetic bead enrichment work?",
  "Why is magnetic bead enrichment important?",
  "When should magnetic bead enrichment be used?",
  "What problems does magnetic bead enrichment solve?",
  "What are the advantages of magnetic bead enrichment?",
  "What are the limitations of magnetic bead enrichment?",
  "How does magnetic bead enrichment improve accuracy?",
  "How does magnetic bead enrichment improve speed?"
];